#:schema node_modules/wrangler/config-schema.json
name = "jolly-hall-8315"
main = "src/worker.js"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
	{ binding = "CHIRPSTACK_KV", id = "2f197b6a380c4451861dc3078c2ae58c" },
]

[observability]
enabled = true
head_sampling_rate = 1
